name: publish

on:
  push:
    tags:
      - "v*"
  workflow_call:
    inputs:
      ref:
        description: "Git ref override"
        type: string
        required: true

permissions:
  contents: write

env:
  PACKAGE_NAME: app_template

jobs:
  # NOTE make sure release exists before concurrent matrix build, to avoid race-conditions
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.ref }}
          generate_release_notes: true

  build:
    needs: [ release ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Pre-built configurations
        include:
          - { idf_target: esp32 }
          - { idf_target: esp32s2 }
    container: espressif/idf:release-v4.4
    env:
      IDF_TARGET: ${{ matrix.idf_target }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Force SoftAP Provisioning
        if: ${{ matrix.idf_target == 'esp32s2' }}
        run: |
          echo "CONFIG_WIFI_AUTO_PROV_TYPE_BLE=n" >> sdkconfig
          echo "CONFIG_WIFI_AUTO_PROV_TYPE_SOFT_AP=y" >> sdkconfig
          echo "CONFIG_BT_ENABLED=n" >> sdkconfig

      - name: Build
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        run: |
          . ${IDF_PATH}/export.sh
          idf.py build

      # This is needed, since softprops/action-gh-release does not support asset renaming
      - name: Prepare assets
        run: |
          mkdir build/upload
          mv build/${{ env.PACKAGE_NAME }}.bin build/upload/${{ env.PACKAGE_NAME }}-${{ matrix.idf_target }}.bin

      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.ref }}
          files: build/upload/*
          fail_on_unmatched_files: true

  finalize:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Success
        if: ${{ needs.build.result == 'success' }}
        uses: softprops/action-gh-release@master # TODO use stable when append_body is supported
        with:
          tag_name: ${{ inputs.ref }}
          append_body: true
          body: |
            
            *<sub>All assets built successfully</sub>*

      - name: Failure
        if: ${{ needs.build.result != 'success' }}
        uses: softprops/action-gh-release@master # TODO use stable when append_body is supported
        with:
          tag_name: ${{ inputs.ref }}
          append_body: true
          body: |
            
            **Some assets failed to build.**
