name: release

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Pre-built configurations
        include:
          - { idf_target: esp32 }
    container: espressif/idf:release-4.4
    env:
      IDF_TARGET: ${{ matrix.idf_target }}
    steps:
      - uses: actions/checkout@v3

      - name: Build
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        run: |
          . ${IDF_PATH}/export.sh
          idf.py build

      - name: Get the upload URL for a release
        uses: bruceadams/get-release@v1.2.3
        id: get_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload firmware.bin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: .pio/build/release/firmware.bin
          asset_name: firmware.bin
          asset_content_type: application/octet-stream
